-- Talking Box V6: persistent memory + internal state
-- Safe to run more than once.

create table if not exists public.memories (
    id bigint generated by default as identity primary key,
    entity_id text not null,
    created_at timestamptz not null default now()
);

alter table public.memories
    add column if not exists memory_type text not null default 'fact';

alter table public.memories
    add column if not exists summary text;

alter table public.memories
    add column if not exists importance double precision not null default 0.5;

alter table public.memories
    add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.memories
    add column if not exists created_at timestamptz not null default now();

create index if not exists memories_entity_created_idx
    on public.memories (entity_id, created_at desc);

create index if not exists memories_entity_importance_idx
    on public.memories (entity_id, importance desc);

update public.entities
set current_state = coalesce(current_state, '{}'::jsonb) || jsonb_build_object(
    'energy', coalesce((current_state->>'energy')::double precision, 0.60),
    'curiosity', coalesce((current_state->>'curiosity')::double precision, 0.72),
    'confidence', coalesce((current_state->>'confidence')::double precision, 0.58),
    'trust', coalesce((current_state->>'trust')::double precision, 0.65),
    'irritation', coalesce((current_state->>'irritation')::double precision, 0.08),
    'anticipation', coalesce((current_state->>'anticipation')::double precision, 0.42)
)
where id = 'voice-box-001';
