-- Talking Box V7.2: grounded social mailbox
--
-- Messages are only deliverable to a verified enrolled speaker id. An anonymous
-- sender is allowed, but their identity remains unknown unless their voice was
-- recognized. No voice embedding or raw audio is stored here.

create table if not exists public.social_messages (
  id bigint generated by default as identity primary key,
  entity_id text not null references public.entities(id) on delete cascade,

  sender_status text not null,
  sender_speaker_id text,
  sender_display_name text,
  sender_voice_session_id text,
  sender_anonymous_id text,
  sender_anonymous_key text,

  recipient_speaker_id text not null,
  recipient_display_name text not null,

  message_text text not null,
  status text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  delivered_at timestamptz,

  constraint social_messages_sender_status_check
    check (sender_status in (
      'recognized',
      'anonymous',
      'unknown',
      'insufficient_audio',
      'unavailable',
      'error'
    )),

  constraint social_messages_status_check
    check (status in ('pending', 'delivered', 'cancelled')),

  constraint social_messages_message_text_check
    check (char_length(trim(message_text)) between 1 and 2000)
);

create index if not exists social_messages_pending_recipient_idx
  on public.social_messages (
    entity_id,
    recipient_speaker_id,
    created_at
  )
  where status = 'pending';

create index if not exists social_messages_sender_idx
  on public.social_messages (
    entity_id,
    sender_speaker_id,
    created_at
  );

alter table public.social_messages enable row level security;

-- No public RLS policies are intentionally created. The entity service uses the
-- Supabase service-role key and is the only component that should read/write the
-- mailbox.

comment on table public.social_messages is
  'Grounded person-to-person messages mediated by an entity. Delivery requires a verified recipient speaker id.';

comment on column public.social_messages.sender_anonymous_key is
  'Temporary boot/session-scoped unknown-voice key. It is not a durable real-world identity.';

comment on column public.social_messages.recipient_speaker_id is
  'Exact enrolled speaker id resolved from device-reported known speakers. Relationship inference is not allowed for routing.';
